import { Platform } from 'react-native';
const BASE_URL = 'https://newdev.emedevents.com';

export default {
  BASE_URL,
  TOKEN: 'TOKEN',
  EMAILOTP: 'EMAILOTP',
  PHONEOTP: 'PHONEOTP',
  STATECOUNT:'STATECOUNT',
  BOARDCOUNT: 'BOARDCOUNT',
  EMAIL:"EMAIL",
  PHONE:"PHONE",
  EMAILSIGNUP:"EMAILSIGNUP",
  PHONESIGNUP:"PHONESIGNUP",
  VERIFYSTATEDATA:"VERIFYSTATEDATA",
  PROFESSION:"PROFESSION",
  WHOLEDATA:"WHOLEDATA",
  PRODATA:"PRODATA",
  EMAVER:"EMAVER",
  MOBVER:"MOBVER",
  COUNTRYCODE:"COUNTRYCODE"
};
