def node_require(script)
  # Resolve script with node to allow for hoisting
 require Pod::Executable.execute_command('node', ['-p',
   "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip 
end
ENV['RCT_NEW_ARCH_ENABLED'] = '1'

node_require('react-native/scripts/react_native_pods.rb');
node_require('react-native-permissions/scripts/setup.rb');

platform :ios, '18'
prepare_react_native_project!
setup_permissions([
 # 'AppTrackingTransparency',
 # 'Bluetooth',
 # 'Calendars',
 # 'CalendarsWriteOnly',
 # 'Camera',
 # 'Contacts',
 # 'FaceID',
 # 'LocationAccuracy',
 # 'LocationAlways',
 # 'LocationWhenInUse',
 'MediaLibrary',
 # 'Microphone',
 # 'Motion',
 # 'Notifications',
  'PhotoLibrary',
  'PhotoLibraryAddOnly',
 # 'Reminders',
 # 'Siri',
  'SpeechRecognition',
 # 'StoreKit',
])
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
 Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
 use_frameworks! :linkage => linkage.to_sym
end
$RNFirebaseAsStaticFramework = true
target 'eMedEvents' do

 config = use_native_modules!

 use_react_native!(
   :path => config[:reactNativePath],
   # An absolute path to your application root.
   :app_path => "#{Pod::Config.instance.installation_root}/.."
 )
pod 'RNFS', :path => '../node_modules/react-native-fs'
pod 'RNFileViewer', :path => '../node_modules/react-native-file-viewer'
 pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'FirebaseInstallations', :modular_headers => true
  pod 'Firebase/Messaging', :modular_headers => true
 post_install do |installer|
   # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
   react_native_post_install(
     installer,
     config[:reactNativePath],
     :mac_catalyst_enabled => false,
     # :ccache_enabled => true
   )
     installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['DEFINES_MODULE'] = 'YES'
        config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
      end
    end
 end
end