import { StyleSheet } from 'react-native';
import Fonts from '../../Themes/Fonts';
import Colorpath from '../../Themes/Colorpath';
import normalize from '../../Utils/Helpers/Dimen'
export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Colorpath.Pagebg
  },
  scrollContent: {
    paddingBottom: 40,
    alignItems: 'center'
  },
  page: {
    width: '100%',
    paddingHorizontal: 16,
    paddingTop: 8
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  logo: { tintColor: undefined },
  topActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10
  },
  langPill: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  langText: {
    fontFamily: Fonts.InterSemiBold,
    fontSize: 13,
    color: Colorpath.black,
    marginRight: 2,
  },
  signInButton: {
    minHeight: 34,
    paddingHorizontal: 14,
    borderRadius: 18,
    backgroundColor: Colorpath.ButtonColr,
    alignItems: 'center',
    justifyContent: 'center',
  },
  signInText: {
    fontFamily: Fonts.InterBold,
    fontSize: 12,
    color: '#FFFFFF',
    letterSpacing: 0.4,
  },
  searchBar: {
    minHeight: 50,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    marginBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#F3F4F6',
  },
  searchText: {
    flex: 1,
    fontFamily: Fonts.InterRegular,
    color: '#9CA3AF',
    fontSize: 13,
  },
  hero: {
    width: normalize(310),
    aspectRatio: 1.8,
    borderRadius: 40,
    overflow: 'hidden',
    padding: 20,
    justifyContent: 'space-between',
    marginBottom: 10,
    alignSelf: 'center',
  },
  heroRadius: { borderRadius: 20 },
  heroBadge: {
    position: 'absolute',
    right: 10,
    top: 0,
    backgroundColor: '#FF8A00',
    borderBottomLeftRadius: 45,
    paddingLeft: 20,
    paddingRight: 12,
    paddingVertical: 18,
    zIndex: 2,
  },
  heroBadgeText: {
    color: '#FFFFFF',
    fontFamily: Fonts.InterExtraBold,
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 15,
    textTransform: 'uppercase',
  },
  heroKicker: {
    color: '#E9ECFF',
    fontFamily: Fonts.InterMedium,
    fontSize: 13,
    marginBottom: 4,
  },
  heroTitle: {
    color: '#FFFFFF',
    fontFamily: Fonts.InterBold,
    fontSize: 22,
    lineHeight: 28,
    width: '85%',
  },
  heroBottomRow: {
    gap: 8,
  },
  heroMeta: {
    minWidth: 0,
    gap: 8,
  },
  heroMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minWidth: 0,
  },
  heroLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    minWidth: 0,
  },
  heroLocationTextWrap: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  heroMetaText: {
    color: '#FFFFFF',
    fontFamily: Fonts.InterMedium,
    fontSize: 13,
    flexShrink: 1,
  },
  heroCreditIcon: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
    tintColor: '#FFFFFF',
  },
  heroButton: {
    borderWidth: 1,
    borderColor: '#FFFFFF',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    minWidth: 116,
    alignItems: 'center',
    flexShrink: 0,
  },
  heroRegisterButton: {
    borderWidth: 1,
    borderColor: '#FFFFFF',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    minWidth: 104,
    alignItems: 'center',
    flexShrink: 0,
  },
  heroButtonText: {
    color: '#FFFFFF',
    fontFamily: Fonts.InterBold,
    fontSize: 14,
    textTransform: 'uppercase',
  },
  bannerCounterWrap: {
    alignSelf: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 6,
    marginTop: 8,
    marginBottom: 16,
  },
  bannerCounterText: {
    color: '#111827',
    fontFamily: Fonts.InterSemiBold,
    fontSize: 12,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 16,
    marginBottom: 12,
  },
  sectionTitle: { fontFamily: Fonts.InterBold, color: '#111827' },
  sectionAction: {
    fontFamily: Fonts.InterSemiBold,
    color: Colorpath.ButtonColr,
  },
  carouselContainer: { width: '100%', marginBottom: 10 },
  paginationContainer: { paddingTop: 8, paddingBottom: 16 },
  activeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#2C4DB9',
    marginHorizontal: -4,
  },
  inactiveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#D1D5DB',
  },
  cardWrap: {
    width: '100%',
    paddingHorizontal: 4,
    alignItems: 'center',
  },
  card: {
    width: '100%',
    maxWidth: normalize(310),
    borderRadius: 24,
    padding: 18,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 15,
    elevation: 4,
    overflow: 'hidden',
    marginBottom: 5,
  },
  cardLight: {
    borderWidth: 1,
    borderColor: '#FDF6B2',
    backgroundColor: '#FFFDF0',
  },
  cardDark: { backgroundColor: '#101626', borderWidth: 0 },
  cardCompact: { paddingBottom: 12 },
  cardImageWrap: {
    position: 'relative',
    width: '100%',
    height: 130,
    borderRadius: 20,
    overflow: 'hidden',
    marginBottom: 12,
  },
  cardImageWrapCompact: { height: 100 },
  cardImage: { flex: 1, width: '100%', justifyContent: 'flex-start' },
  cardImageRadius: { borderRadius: 20 },
  badge: {
    position: 'absolute',
    right: 10,
    top: 10,
    backgroundColor: '#FF8A00',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  badgeText: {
    color: '#FFFFFF',
    fontFamily: Fonts.InterExtraBold,
    fontSize: 10,
    lineHeight: 11,
    textAlign: 'center',
  },
  cardTitle: {
    fontFamily: Fonts.InterBold,
    color: '#111827',
    lineHeight: 22,
    marginTop: 4,
  },
  cardTitleDark: { color: '#FFFFFF' },
  cardMeta: {
    fontFamily: Fonts.InterRegular,
    color: '#6B7280',
    lineHeight: 18,
    marginTop: 4,
  },
  cardMetaDark: { color: '#D9E2FF' },
  metaGroup: { gap: 8, marginTop: 10 },
  infoRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  infoText: { fontFamily: Fonts.InterRegular, color: '#4B5563', flexShrink: 1 },
  creditRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  creditIcon: {
    width: 16,
    height: 16,
    tintColor: '#2C4DB9',
    resizeMode: 'contain',
  },
  creditIconDark: { tintColor: '#FFFFFF' },
  divider: {
    height: 1,
    width: '100%',
    backgroundColor: '#F3F4F6',
    marginTop: 12,
    marginBottom: 12,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  priceText: { fontFamily: Fonts.InterExtraBold, color: Colorpath.ButtonColr },
  priceTextDark: { color: '#8EA7FF' },
  ctaPill: {
    borderRadius: 14,
    backgroundColor: '#111827',
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  ctaPillDark: { backgroundColor: '#FF8A00' },
  ctaText: { color: '#FFFFFF', fontFamily: Fonts.InterBold },
  ctaTextDark: { color: '#FFFFFF' },
  featureCardOuter: {
    width: '100%',
    paddingHorizontal: 4,
    alignItems: 'center',
  },
  featureCard: {
    width: '100%',
    maxWidth: normalize(310),
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#FF8A00',
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 15,
    elevation: 4,
    overflow: 'hidden',
  },
  featureCardDark: {
    backgroundColor: '#101626',
    borderColor: '#101626',
  },
  featureCardCompact: {
    paddingVertical: 14,
  },
  featureHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  featureLogoCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#FFF7EC',
    borderWidth: 1,
    borderColor: '#F3E3C3',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    flexShrink: 0,
  },
  featureLogoImage: {
    width: '100%',
    height: '100%',
  },
  featureLogoFallback: {
    color: '#FF8A00',
    fontFamily: Fonts.InterBold,
    fontSize: 12,
  },
  featureOrgName: {
    flex: 1,
    fontFamily: Fonts.InterMedium,
    color: '#4B5563',
    fontSize: 13,
  },
  featureOrgNameDark: {
    color: '#D9E2FF',
  },
  featureTitle: {
    fontFamily: Fonts.InterBold,
    color: '#111827',
    fontSize: 20,
    lineHeight: 26,
  },
  featureTitleDark: {
    color: '#FFFFFF',
  },
  featureMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 10,
  },
  featureMetaText: {
    flex: 1,
    fontFamily: Fonts.InterMedium,
    color: '#333333',
    fontSize: 13,
  },
  featureMetaTextDark: {
    color: '#E5E7EB',
  },
  featureBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: 14,
  },
  featureCmePill: {
    flex: 1,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  featureCmeText: {
    fontFamily: Fonts.InterSemiBold,
    fontSize: 12,
    color: '#111827',
  },
  featureCmeTextDark: {
    color: '#FFFFFF',
  },
  featurePricePill: {
    backgroundColor: '#111827',
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
    minWidth: 120,
    alignItems: 'center',
    flexShrink: 0,
  },
  featurePriceText: {
    color: '#FFFFFF',
    fontFamily: Fonts.InterBold,
    fontSize: 14,
  },
  featureButton: {
    marginTop: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#FF8A00',
    paddingVertical: 10,
    alignItems: 'center',
  },
  featureButtonText: {
    color: '#FF8A00',
    fontFamily: Fonts.InterBold,
    fontSize: 13,
    textTransform: 'uppercase',
  },
  panel: {
    borderRadius: 24,
    backgroundColor: '#1E3A8A',
    padding: 20,
    marginBottom: 20,
    width: '100%',
  },
  panelTitle: {
    color: '#FFFFFF',
    fontFamily: Fonts.InterBold,
    fontSize: 18,
    textAlign: 'center',
  },
  panelSubTitle: {
    color: '#BFDBFE',
    fontFamily: Fonts.InterRegular,
    fontSize: 13,
    textAlign: 'center',
    marginTop: 6,
    marginBottom: 20,
  },
  selectorRow: { flexDirection: 'row', gap: 12 },
  selectorBox: {
    flex: 1,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  selectorLabel: {
    fontFamily: Fonts.InterRegular,
    color: '#6B7280',
    fontSize: 12,
    marginBottom: 4,
  },
  selectorValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectorValue: {
    fontFamily: Fonts.InterSemiBold,
    color: '#111827',
    fontSize: 15,
  },
  chipRow: {
    paddingBottom: 10,
    marginTop: 4,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  chip: {
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginRight: 10,
    marginBottom: 12,
  },
  chipActive: { backgroundColor: '#2C4DB9', borderColor: '#2C4DB9' },
  chipText: { fontFamily: Fonts.InterSemiBold, color: '#6B7280' },
  chipTextActive: { color: '#FFFFFF' },
  marketHeader: { justifyContent: 'center', alignSelf: 'center', marginTop: 24, marginBottom: 16, width: normalize(180) },
  marketTitle: {
    fontFamily: Fonts.InterBold,
    color: '#111827',
    fontSize: 20,
    textAlign: 'center',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 24,
    width: '100%',
    // backgroundColor:Colorpath.SkyBG,
  },
  statTileFull: {
    width: '100%',
    backgroundColor: Colorpath.SkyBG,
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statTile: {
    width: '48%',
    backgroundColor: Colorpath.SkyBG,
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statValue: {
    fontFamily: Fonts.InterExtraBold,
    color: Colorpath.ButtonColr,
    textAlign: 'center',
  },
  statLabel: {
    fontFamily: Fonts.InterSemiBold,
    color: '#42526B',
    textAlign: 'center',
    marginTop: 6,
  },
  membershipCard: {
    borderRadius: 28,
    paddingTop: 30,
    width: normalize(290),
    height: normalize(465),
    alignItems: 'center',
    alignSelf: 'center',
  },
  membershipHeader: {
    alignItems: 'center',
    alignSelf: 'center'
  },
  membershipWrapper: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  membershipTitle: {
    color: '#FFFFFF',
    fontFamily: Fonts.InterBold,
    fontSize: 30,
    textAlign: 'center',
    marginBottom: 10,
    alignItems: "center"
  },
  membershipPointsList: {
    marginTop: 16,
    gap: 12,
    alignItems: 'center',
  },
  membershipPoint: {
    flexDirection: 'row',
    alignItems: 'center',
    width: normalize(230),
    gap: 12,
  },
  membershipFeatureText: {
    flexDirection: 'row',
    alignItems: 'center',
    width: normalize(180),
    marginTop: normalize(5)
  },
  membershipPointText: {
    color: '#FFFFFF',
    fontFamily: Fonts.InterSemiBold,
    fontSize: 14,
    flexShrink: 1,
  },
  moreFeatures: {
    marginTop: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#FFFFFF',
    alignSelf: 'center',
  },
  moreFeaturesText: {
    color: '#FFB08E',
    fontFamily: Fonts.InterBold,
    fontSize: 14,
    opacity: 0.9,
    textDecorationLine: 'underline'
  },
  membershipButton: {
    marginTop: 14,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingVertical: 14,
    width: '90%',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  membershipButtonText: {
    color: Colorpath.ButtonColr,
    fontFamily: Fonts.InterBold,
    fontSize: 18,
  },
  membershipArtwork: {
    width: '100%',
    height: normalize(180),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
    marginBottom: 8,
  },
  membershipImage: {
    width: normalize(240),
    height: normalize(160),
    alignSelf: 'center',
  },
  membershipOrb: {
    position: 'absolute',
    width: '88%',
    height: '92%',
    zIndex: 0,
    top: 0,
    tintColor: '#F4BC00',
  },
  membershipDoctor: {
    width: '76%',
    height: '100%',
    zIndex: 1,
    marginTop: 8,
  },
});
