import { StyleSheet, Platform } from 'react-native';
import Fonts from '../../Themes/Fonts';
import Colorpath from '../../Themes/Colorpath';
import normalize from '../../Utils/Helpers/Dimen';
export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Colorpath.Pagebg
  },
  scrollContent: {
    paddingBottom: 4,
    alignItems: 'center'
  },
  page: {
    width: '100%',
    paddingHorizontal: 16,
    paddingTop: 8
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  logo: { tintColor: undefined },
  topActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10
  },
  langPill: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  langText: {
    fontFamily: Fonts.InterSemiBold,
    fontSize: 13,
    color: Colorpath.black,
    marginRight: 2,
  },
  signInButton: {
    minHeight: 34,
    paddingHorizontal: 14,
    borderRadius: 18,
    backgroundColor: Colorpath.ButtonColr,
    alignItems: 'center',
    justifyContent: 'center',
  },
  signInText: {
    fontFamily: Fonts.InterBold,
    fontSize: 12,
    color: '#FFFFFF',
    letterSpacing: 0.4,
  },
  searchBar: {
    minHeight: 52,
    borderRadius: 10,
    backgroundColor: '#F9FAFC',
    paddingHorizontal: 16,
    marginBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: '#DADADA',
  },
  searchText: {
    fontFamily: Fonts.InterMedium,
    color: '#798492',
    fontSize: 15,
  },
  searchTextScroll: {
    flex: 1,
  },
  searchTextScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingRight: 8,
  },
  hero: {
    width: normalize(310),
    // aspectRatio: Platform.OS === 'android' ? 1.2 : 1.8,
    borderRadius: 40,
    overflow: 'hidden',
    padding: 20,
    justifyContent: 'space-between',
    marginBottom: 10,
    alignSelf: 'center',
  },
  heroRadius: { borderRadius: 20 },
  heroBadge: {
    position: 'absolute',
    right: 10,
    top: 0,
    backgroundColor: '#FF8A00',
    borderBottomLeftRadius: 45,
    paddingLeft: 20,
    paddingRight: 12,
    paddingVertical: 18,
    zIndex: 2,
  },
  heroBadgeText: {
    color: '#FFFFFF',
    fontFamily: Fonts.InterExtraBold,
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 15,
    textTransform: 'uppercase',
  },
  heroKicker: {
    color: '#E9ECFF',
    fontFamily: Fonts.InterMedium,
    fontSize: 13,
    marginBottom: 4,
  },
  heroTitle: {
    color: '#FFFFFF',
    fontFamily: Fonts.InterBold,
    fontSize: Platform.OS === 'android' ? 18 : 22,
    lineHeight: Platform.OS === 'android' ? 24 : 28,
    width: '85%',
  },
  heroBottomRow: {
    gap: 8,
  },
  heroMeta: {
    minWidth: 0,
    gap: 8,
  },
  heroMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minWidth: 0,
  },
  heroLocationRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 10,
    minWidth: 0,
  },
  heroLocationTextWrap: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingRight: 6,
  },
  heroMetaText: {
    color: '#FFFFFF',
    fontFamily: Fonts.InterMedium,
    fontSize: 13,
    flexShrink: 1,
  },
  heroCreditIcon: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
    tintColor: '#FFFFFF',
  },
  heroButton: {
    borderWidth: 1,
    borderColor: '#FFFFFF',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    minWidth: 116,
    alignItems: 'center',
    flexShrink: 0,
  },
  heroRegisterButton: {
    borderWidth: 1,
    borderColor: '#FFFFFF',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 10,
    minWidth: 0,
    maxWidth: '42%',
    alignItems: 'center',
    flexShrink: 0,
  },
  heroButtonText: {
    color: '#FFFFFF',
    fontFamily: Fonts.InterBold,
    fontSize: 12,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  bannerCounterWrap: {
    alignSelf: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 6,
    marginTop: 6,
    marginBottom: 8,
  },
  bannerCounterText: {
    color: '#111827',
    fontFamily: Fonts.InterSemiBold,
    fontSize: 12,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
    marginBottom: 8,
  },
  sectionTitle: { fontFamily: Fonts.InterBold, color: '#111827' },
  sectionAction: {
    fontFamily: Fonts.InterSemiBold,
    color: Colorpath.ButtonColr,
  },
  carouselContainer: { width: '100%', marginBottom: 4 },
  paginationContainer: { paddingTop: 8, paddingBottom: 10 },
  activeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#2C4DB9',
    marginHorizontal: -4,
  },
  inactiveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#D1D5DB',
  },
  shimmerHeroWrap: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 18,
  },
  shimmerHero: {
    height: normalize(175),
    borderRadius: 20,
    padding: 20,
  },
  shimmerHeroBottom: {
    marginTop: normalize(38),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  shimmerCardWrap: {
    width: '100%',
    alignItems: 'center',
  },
  shimmerCard: {
    width: normalize(310),
    minHeight: normalize(245),
    borderRadius: 24,
    padding: 18,
  },
  shimmerLiveCard: {
    width: normalize(360),
    minHeight: normalize(250),
    borderRadius: 18,
  },
  shimmerFreeCard: {
    width: normalize(360),
    minHeight: normalize(205),
    borderRadius: 18,
  },
  shimmerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  shimmerCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    marginRight: 12,
  },
  shimmerLineShort: {
    width: normalize(110),
    height: 14,
    borderRadius: 7,
    marginBottom: 14,
  },
  shimmerLineMedium: {
    width: normalize(170),
    height: 14,
    borderRadius: 7,
    marginBottom: 12,
  },
  shimmerLineWide: {
    width: normalize(250),
    height: 18,
    borderRadius: 9,
    marginBottom: 12,
  },
  shimmerFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
  },
  shimmerPill: {
    width: normalize(155),
    height: 38,
    borderRadius: 19,
  },
  shimmerPrice: {
    width: normalize(85),
    height: 20,
    borderRadius: 10,
  },
  shimmerButtonSmall: {
    width: normalize(104),
    height: 36,
    borderRadius: 8,
  },
  shimmerChipsSection: {
    width: '100%',
  },
  shimmerChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingBottom: 10,
  },
  shimmerChip: {
    width: normalize(118),
    height: 36,
    borderRadius: 18,
    marginRight: 10,
    marginBottom: 12,
  },
  liveSection: {
    width: '100%',
    backgroundColor: Colorpath.Pagebg,
    paddingTop: 4,
    marginTop: 8,
    marginBottom: 6,
  },
  liveHeader: {
    minHeight: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  liveSectionTitle: {
    color: '#111827',
    fontFamily: Fonts.InterBold,
    fontSize: 18,
  },
  liveViewAll: {
    color: Colorpath.ButtonColr,
    fontFamily: Fonts.InterBold,
    fontSize: 13,
  },
  liveCardWrap: {
    width: '93%',
    alignItems: 'center',
  },
  liveCard: {
    width: '100%',
    maxWidth: normalize(390),
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
  },
  liveCardTop: {
    backgroundColor: '#CBEFFF',
    paddingHorizontal: 28,
    paddingTop: 20,
    paddingBottom: 18,
    minHeight: 142,
  },
  liveLocationPill: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colorpath.ButtonColr,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    marginBottom: 12,
    maxWidth: '90%',
  },
  liveLocationText: {
    color: '#FFFFFF',
    fontFamily: Fonts.InterSemiBold,
    fontSize: 11,
    marginLeft: 3,
  },
  liveTitle: {
    color: '#000000',
    fontFamily: Fonts.InterBold,
    fontSize: 18,
    lineHeight: 24,
  },
  liveOrg: {
    flex: 1,
    color: '#000000',
    fontFamily: Fonts.InterMedium,
    fontSize: 12,
  },
  liveOrgRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    minWidth: 0,
  },
  liveOrgLogo: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D9E7F0',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    marginRight: 8,
    flexShrink: 0,
  },
  liveOrgLogoImage: {
    width: '100%',
    height: '100%',
  },
  liveOrgLogoFallback: {
    color: Colorpath.ButtonColr,
    fontFamily: Fonts.InterBold,
    fontSize: 10,
  },
  liveCardBottom: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 20,
  },
  liveDateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
  },
  liveDateText: {
    flex: 1,
    color: '#333333',
    fontFamily: Fonts.InterRegular,
    fontSize: 14,
    marginLeft: 12,
  },
  liveFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  liveCreditPill: {
    flex: 1,
    minHeight: 38,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 999,
    justifyContent: 'center',
    paddingHorizontal: 16,
    backgroundColor: '#FFFFFF',
  },
  liveCreditText: {
    color: '#333333',
    fontFamily: Fonts.InterBold,
    fontSize: 12,
  },
  livePriceText: {
    color: Colorpath.ButtonColr,
    fontFamily: Fonts.InterExtraBold,
    fontSize: 18,
    flexShrink: 0,
  },
  liveButton: {
    minHeight: 36,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colorpath.ButtonColr,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 14,
    paddingHorizontal: 14,
  },
  liveButtonText: {
    color: Colorpath.ButtonColr,
    fontFamily: Fonts.InterBold,
    fontSize: 13,
    textTransform: 'uppercase',
  },
  livePaginationContainer: {
    paddingTop: 8,
    paddingBottom: 8,
  },
  liveActiveDot: {
    width: 18,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#8D8D8D',
    marginHorizontal: -4,
  },
  liveInactiveDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#D1D5DB',
  },
  cardWrap: {
    width: '100%',
    paddingHorizontal: 4,
    alignItems: 'center',
  },
  card: {
    width: '100%',
    maxWidth: normalize(310),
    borderRadius: 24,
    padding: 18,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 15,
    elevation: 4,
    overflow: 'hidden',
    marginBottom: 5,
  },
  cardLight: {
    borderWidth: 1,
    borderColor: '#FDF6B2',
    backgroundColor: '#FFFDF0',
  },
  cardDark: { backgroundColor: '#101626', borderWidth: 0 },
  cardCompact: { paddingBottom: 12 },
  cardImageWrap: {
    position: 'relative',
    width: '100%',
    height: 130,
    borderRadius: 20,
    overflow: 'hidden',
    marginBottom: 12,
  },
  cardImageWrapCompact: { height: 100 },
  cardImage: { flex: 1, width: '100%', justifyContent: 'flex-start' },
  cardImageRadius: { borderRadius: 20 },
  badge: {
    position: 'absolute',
    right: 10,
    top: 10,
    backgroundColor: '#FF8A00',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  badgeText: {
    color: '#FFFFFF',
    fontFamily: Fonts.InterExtraBold,
    fontSize: 10,
    lineHeight: 11,
    textAlign: 'center',
  },
  cardTitle: {
    fontFamily: Fonts.InterBold,
    color: '#111827',
    lineHeight: 22,
    marginTop: 4,
  },
  cardTitleDark: { color: '#FFFFFF' },
  cardMeta: {
    fontFamily: Fonts.InterRegular,
    color: '#6B7280',
    lineHeight: 18,
    marginTop: 4,
  },
  cardMetaDark: { color: '#D9E2FF' },
  metaGroup: { gap: 8, marginTop: 10 },
  infoRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  infoText: { fontFamily: Fonts.InterRegular, color: '#4B5563', flexShrink: 1 },
  creditRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  creditIcon: {
    width: 16,
    height: 16,
    tintColor: '#2C4DB9',
    resizeMode: 'contain',
  },
  creditIconDark: { tintColor: '#FFFFFF' },
  divider: {
    height: 1,
    width: '100%',
    backgroundColor: '#F3F4F6',
    marginTop: 12,
    marginBottom: 12,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  priceText: { fontFamily: Fonts.InterExtraBold, color: Colorpath.ButtonColr },
  priceTextDark: { color: '#8EA7FF' },
  ctaPill: {
    borderRadius: 14,
    backgroundColor: '#111827',
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  ctaPillDark: { backgroundColor: '#FF8A00' },
  ctaText: { color: '#FFFFFF', fontFamily: Fonts.InterBold },
  ctaTextDark: { color: '#FFFFFF' },
  popularCardWrap: {
    width: '100%',
    paddingHorizontal: 4,
    alignItems: 'center',
  },
  popularCard: {
    width: '100%',
    maxWidth: normalize(390),
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F4B000',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 15,
    elevation: 4,
  },
  popularByText: {
    fontFamily: Fonts.InterMedium,
    color: '#4B5563',
    fontSize: 13,
    marginBottom: 8,
  },
  popularTitle: {
    fontFamily: Fonts.InterBold,
    color: '#111827',
    lineHeight: 22,
  },
  popularMetaGroup: {
    gap: 10,
    marginTop: 14,
  },
  popularDivider: {
    height: 1,
    width: '100%',
    backgroundColor: '#D1D5DB',
    marginTop: 16,
    marginBottom: 14,
  },
  popularPrice: {
    fontFamily: Fonts.InterExtraBold,
    color: '#111827',
  },
  popularFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  popularButton: {
    minHeight: 36,
    borderRadius: 10,
    backgroundColor: '#111827',
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  popularButtonText: {
    color: '#FFFFFF',
    fontFamily: Fonts.InterBold,
    fontSize: 12,
    textTransform: 'uppercase',
  },
  featureCardOuter: {
    width: '100%',
    paddingHorizontal: 4,
    alignItems: 'center',
  },
  featureCard: {
    width: '100%',
    maxWidth: normalize(310),
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#FF8A00',
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 15,
    elevation: 4,
    overflow: 'hidden',
  },
  featureCardDark: {
    backgroundColor: '#101626',
    borderColor: '#101626',
  },
  featureCardCompact: {
    paddingVertical: 14,
  },
  featureHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  featureLogoCircle: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#FFF7EC',
    borderWidth: 1,
    borderColor: '#F3E3C3',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    flexShrink: 0,
  },
  featureLogoImage: {
    width: '100%',
    height: '100%',
  },
  featureLogoFallback: {
    color: '#FF8A00',
    fontFamily: Fonts.InterBold,
    fontSize: 12,
  },
  featureOrgName: {
    flex: 1,
    fontFamily: Fonts.InterMedium,
    color: '#4B5563',
    fontSize: 13,
  },
  featureOrgNameDark: {
    color: '#D9E2FF',
  },
  featureTitle: {
    fontFamily: Fonts.InterBold,
    color: '#111827',
    fontSize: 20,
    lineHeight: 26,
  },
  featureTitleDark: {
    color: '#FFFFFF',
  },
  featureSpecialityWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    marginBottom: 10,
    gap: 6,
  },
  featureSpecialityPill: {
    maxWidth: '48%',
    minHeight: 24,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  featureSpecialityText: {
    flexShrink: 1,
    color: '#111827',
    fontFamily: Fonts.InterMedium,
    fontSize: 12,
  },
  featureSpecialityMore: {
    minHeight: 24,
    borderRadius: 999,
    paddingHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  featureSpecialityMoreText: {
    color: '#6B7280',
    fontFamily: Fonts.InterBold,
    fontSize: 14,
  },
  featureMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 10,
  },
  featureMetaText: {
    flex: 1,
    fontFamily: Fonts.InterMedium,
    color: '#333333',
    fontSize: 13,
  },
  featureMetaTextDark: {
    color: '#E5E7EB',
  },
  featureBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: 14,
  },
  featureCmePill: {
    flex: 1,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  featureCmeText: {
    fontFamily: Fonts.InterSemiBold,
    fontSize: 12,
    color: '#111827',
  },
  featureCmeTextDark: {
    color: '#FFFFFF',
  },
  featurePricePill: {
    backgroundColor: '#111827',
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 10,
    minWidth: 120,
    alignItems: 'center',
    flexShrink: 0,
  },
  featurePriceText: {
    color: '#FFFFFF',
    fontFamily: Fonts.InterBold,
    fontSize: 14,
  },
  featureButton: {
    marginTop: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#FF8A00',
    paddingVertical: 10,
    alignItems: 'center',
  },
  featureButtonText: {
    color: '#FF8A00',
    fontFamily: Fonts.InterBold,
    fontSize: 13,
    textTransform: 'uppercase',
  },
  freeCardWrap: {
    width: '100%',
    paddingHorizontal: 4,
    alignItems: 'center',
  },
  freeCard: {
    width: '100%',
    maxWidth: normalize(390),
    minHeight: normalize(205),
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 24,
    paddingVertical: 24,
    justifyContent: 'space-between',
  },
  freeTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: 0,
    marginBottom: 12,
  },
  freeTypePill: {
    maxWidth: '42%',
    minHeight: 22,
    borderRadius: 999,
    backgroundColor: Colorpath.ButtonColr,
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 10,
    flexShrink: 0,
  },
  freeTypeText: {
    color: '#FFFFFF',
    fontFamily: Fonts.InterBold,
    fontSize: 12,
    marginLeft: 4,
  },
  freeDateText: {
    flex: 1,
    color: '#333333',
    fontFamily: Fonts.InterSemiBold,
    fontSize: 13,
  },
  freeOrgText: {
    color: '#333333',
    fontFamily: Fonts.InterRegular,
    fontSize: 14,
    marginBottom: 8,
  },
  freeTitleText: {
    color: '#000000',
    fontFamily: Fonts.InterBold,
    fontSize: 18,
    lineHeight: 23,
    marginBottom: 18,
  },
  freeBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
  },
  freeCreditPill: {
    flex: 1,
    minHeight: 38,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 14,
    justifyContent: 'center',
  },
  freeCreditText: {
    color: '#333333',
    fontFamily: Fonts.InterBold,
    fontSize: 12,
  },
  freePriceText: {
    color: Colorpath.ButtonColr,
    fontFamily: Fonts.InterExtraBold,
    fontSize: 18,
    flexShrink: 0,
  },
  freeButton: {
    minHeight: 38,
    borderRadius: 10,
    backgroundColor: Colorpath.ButtonColr,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 14,
    paddingHorizontal: 16,
  },
  freeButtonText: {
    color: '#FFFFFF',
    fontFamily: Fonts.InterBold,
    fontSize: 13,
    textTransform: 'uppercase',
  },
  panel: {
    borderRadius: 24,
    backgroundColor: '#1E3A8A',
    padding: 20,
    marginBottom: 10,
    width: '100%',
  },
  requirementsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 12,
  },
  requirementsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  requirementsIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#D9E7F0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    backgroundColor: '#F9FBFF',
  },
  requirementsHeaderText: {
    flex: 1,
  },
  requirementsTitle: {
    color: '#111827',
    fontFamily: Fonts.InterBold,
    fontSize: 15,
  },
  requirementsSubtitle: {
    color: '#9CA3AF',
    fontFamily: Fonts.InterRegular,
    fontSize: 11,
    marginTop: 2,
  },
  requirementsShimmerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  requirementsShimmerIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    marginRight: 10,
  },
  requirementsShimmerHeaderText: {
    flex: 1,
  },
  requirementsShimmerTitle: {
    width: normalize(130),
    height: 14,
    borderRadius: 7,
    marginBottom: 6,
  },
  requirementsShimmerSubtitle: {
    width: normalize(165),
    height: 10,
    borderRadius: 5,
  },
  requirementsShimmerRow: {
    flexDirection: 'row',
    columnGap: 12,
  },
  requirementsShimmerField: {
    flex: 1,
    height: 40,
    borderRadius: 10,
  },
  panelTitle: {
    color: '#FFFFFF',
    fontFamily: Fonts.InterBold,
    fontSize: 18,
    textAlign: 'center',
  },
  panelSubTitle: {
    color: '#BFDBFE',
    fontFamily: Fonts.InterRegular,
    fontSize: 13,
    textAlign: 'center',
    marginTop: 6,
    marginBottom: 14,
  },
  selectorRow: {
    flexDirection: 'row',
    columnGap: 12,
  },
  selectorPlain: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 2,
    paddingVertical: 2,
    justifyContent: 'center',
  },
  selectorLabel: {
    fontFamily: Fonts.InterRegular,
    color: '#111827',
    fontSize: 11,
    marginBottom: 4,
  },
  selectorValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectorValue: {
    fontFamily: Fonts.InterSemiBold,
    color: Colorpath.ButtonColr,
    fontSize: 11,
  },
  chipRow: {
    paddingBottom: 10,
    marginTop: 4,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  chipScrollContent: {
    paddingBottom: 10,
    paddingRight: 16,
  },
  chipColumn: {
    marginRight: 10,
  },
  chip: {
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginBottom: 12,
  },
  chipActive: { backgroundColor: '#2C4DB9', borderColor: '#2C4DB9' },
  chipText: { fontFamily: Fonts.InterSemiBold, color: '#6B7280' },
  chipTextActive: { color: '#FFFFFF' },
  marketHeader:
   { justifyContent: 'center', alignSelf: 'center', marginTop: 12, marginBottom: 10, width: normalize(185) },
  marketTitle: {
    fontFamily: Fonts.InterBold,
    color: '#111827',
    fontSize: 20,
    textAlign: 'center',
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 12,
    width: '100%',
    // backgroundColor:Colorpath.SkyBG,
  },
  statTileFull: {
    width: '100%',
    backgroundColor: Colorpath.SkyBG,
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statTile: {
    width: '48%',
    backgroundColor: Colorpath.SkyBG,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statValue: {
    fontFamily: Fonts.InterExtraBold,
    color: Colorpath.ButtonColr,
    textAlign: 'center',
  },
  statLabel: {
    fontFamily: Fonts.InterSemiBold,
    color: '#42526B',
    textAlign: 'center',
    marginTop: 6,
  },
  membershipCard: {
    borderRadius: 28,
    paddingTop: 30,
    paddingBottom: 20,
    width: normalize(300),
    minHeight: normalize(465),
    alignItems: 'center',
    alignSelf: 'center',
    overflow: 'hidden',
  },
  membershipHeader: {
    alignItems: 'center',
    alignSelf: 'center'
  },
  membershipWrapper: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  membershipTitle: {
    color: '#FFFFFF',
    fontFamily: Fonts.InterBold,
    fontSize: 30,
    textAlign: 'center',
    marginBottom: 10,
    alignItems: "center"
  },
  membershipPointsList: {
    marginTop: 16,
    gap: 12,
    alignItems: 'center',
  },
  membershipPoint: {
    flexDirection: 'row',
    alignItems: 'center',
    width: normalize(230),
    gap: 12,
  },
  membershipFeatureText: {
    flexDirection: 'row',
    alignItems: 'center',
    width: normalize(180),
    marginTop: normalize(5)
  },
  membershipPointText: {
    color: '#FFFFFF',
    fontFamily: Fonts.InterSemiBold,
    fontSize: 14,
    flexShrink: 1,
  },
  moreFeatures: {
    marginTop: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#FFFFFF',
    alignSelf: 'center',
  },
  moreFeaturesText: {
    color: '#FFB08E',
    fontFamily: Fonts.InterBold,
    fontSize: 14,
    opacity: 0.9,
    textDecorationLine: 'underline'
  },
  membershipButton: {
    marginTop: 14,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingVertical: 14,
    width: '92%',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  membershipButtonText: {
    color: Colorpath.ButtonColr,
    fontFamily: Fonts.InterBold,
    fontSize: 18,
  },
  membershipArtwork: {
    width: '100%',
    height: Platform.OS === 'android' ? normalize(120) : normalize(180),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
    marginBottom: 8,
  },
  membershipImage: {
    width: Platform.OS === 'android' ? normalize(180) : normalize(240),
    height: Platform.OS === 'android' ? normalize(110) : normalize(160),
    alignSelf: 'center',
  },
  membershipOrb: {
    position: 'absolute',
    width: '88%',
    height: '92%',
    zIndex: 0,
    top: 0,
    tintColor: '#F4BC00',
  },
  membershipDoctor: {
    width: '76%',
    height: '100%',
    zIndex: 1,
    marginTop: 8,
  },
});
